//Code Generated by Jenga.NET 
            using System.Drawing;
            using System.Windows.Forms;

			namespace PatientRecordManagement.Clinic.Skin
{
    partial class Skin
    {

        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Skin));
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject1 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption1 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject1 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption18 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject18 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject18 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject2 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject2 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption2 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject3 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject3 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption3 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject4 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject4 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption4 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject5 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption5 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject5 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject6 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption6 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject6 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject7 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject7 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption7 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject8 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption8 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject8 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject9 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption9 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject9 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject10 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption10 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject10 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject11 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption11 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject11 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject12 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption12 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject12 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject13 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption13 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject13 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject14 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption14 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject14 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject15 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption15 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject15 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject16 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption16 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject16 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject17 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption17 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject17 = new Kimtoo.ValidationProvider.ValidationObject();
            this.Alert = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.validationProvider = new Kimtoo.ValidationProvider.ValidationProvider();
            this.AppBarCh = new Bunifu.Utils.BunifuAppBar();
            this.pnlContent = new System.Windows.Forms.Panel();
            this.bunifuDropdown3 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuDropdown2 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuDropdown1 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.labelC10 = new System.Windows.Forms.Label();
            this.labelC4 = new System.Windows.Forms.Label();
            this.bunifuDropdownC1 = new Bunifu.UI.WinForms.BunifuDropdown();
            this.labelC5 = new System.Windows.Forms.Label();
            this.labelC7 = new System.Windows.Forms.Label();
            this.labelS11 = new System.Windows.Forms.Label();
            this.bunifuTextBoxS5 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelS3 = new System.Windows.Forms.Label();
            this.dtDateS1 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.lblCreatedAt = new System.Windows.Forms.Label();
            this.lblBottom = new System.Windows.Forms.Label();
            this.btnCancelS1 = new System.Windows.Forms.Button();
            this.btnAddS1 = new System.Windows.Forms.Button();
            this.bindingProvider = new Kimtoo.BindingProvider.BindingProvider();
            this.themeProvider = new Kimtoo.ThemeProvider.ThemeProvider();
            this.bunifuFormDock = new Bunifu.UI.WinForms.BunifuFormDock();
            this.openFileDialog = new System.Windows.Forms.OpenFileDialog();
            this.saveFileDialog = new System.Windows.Forms.SaveFileDialog();
            this.pnlContent.SuspendLayout();
            this.SuspendLayout();
            // 
            // Alert
            // 
            this.Alert.AllowDragging = false;
            this.Alert.AllowMultipleViews = true;
            this.Alert.ClickToClose = true;
            this.Alert.DoubleClickToClose = true;
            this.Alert.DurationAfterIdle = 3000;
            this.Alert.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.ErrorOptions.ActionBorderRadius = 1;
            this.Alert.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Alert.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Alert.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.Alert.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.Alert.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.Alert.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Alert.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.Alert.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.Alert.ErrorOptions.IconLeftMargin = 12;
            this.Alert.FadeCloseIcon = false;
            this.Alert.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.Alert.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.InformationOptions.ActionBorderRadius = 1;
            this.Alert.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Alert.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Alert.InformationOptions.BackColor = System.Drawing.Color.White;
            this.Alert.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.Alert.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.Alert.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Alert.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.Alert.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.Alert.InformationOptions.IconLeftMargin = 12;
            this.Alert.Margin = 10;
            this.Alert.MaximumSize = new System.Drawing.Size(0, 0);
            this.Alert.MaximumViews = 7;
            this.Alert.MessageRightMargin = 15;
            this.Alert.MinimumSize = new System.Drawing.Size(0, 0);
            this.Alert.ShowBorders = false;
            this.Alert.ShowCloseIcon = false;
            this.Alert.ShowIcon = true;
            this.Alert.ShowShadows = true;
            this.Alert.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.SuccessOptions.ActionBorderRadius = 1;
            this.Alert.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Alert.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Alert.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.Alert.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.Alert.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.Alert.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Alert.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.Alert.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.Alert.SuccessOptions.IconLeftMargin = 12;
            this.Alert.ViewsMargin = 7;
            this.Alert.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.WarningOptions.ActionBorderRadius = 1;
            this.Alert.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Alert.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Alert.WarningOptions.BackColor = System.Drawing.Color.White;
            this.Alert.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.Alert.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.Alert.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Alert.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.Alert.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.Alert.WarningOptions.IconLeftMargin = 12;
            this.Alert.ZoomCloseIcon = true;
            // 
            // validationProvider
            // 
            this.validationProvider.ErrorColor = System.Drawing.Color.Crimson;
            // 
            // AppBarCh
            // 
            this.AppBarCh.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(43)))));
            this.AppBarCh.ControlBoxColor = System.Drawing.Color.WhiteSmoke;
            this.AppBarCh.ControlBoxColorActive = System.Drawing.Color.White;
            this.AppBarCh.Dock = System.Windows.Forms.DockStyle.Top;
            this.AppBarCh.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.AppBarCh.ForeColor = System.Drawing.Color.White;
            this.AppBarCh.Icon = ((System.Drawing.Image)(resources.GetObject("AppBarCh.Icon")));
            bindingObject1.Data = "";
            bindingObject1.Property = "Text";
            bindingObject1.TwoWay = true;
            this.bindingProvider.SetLink(this.AppBarCh, bindingObject1);
            themeOption1.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.AppBarCh, themeOption1);
            validationObject1.CustomErrorMessage = "";
            validationObject1.Optional = false;
            validationObject1.PropertyName = "Text";
            validationObject1.Regex = null;
            validationObject1.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.AppBarCh, validationObject1);
            this.AppBarCh.Location = new System.Drawing.Point(0, 0);
            this.AppBarCh.Name = "AppBarCh";
            this.AppBarCh.Size = new System.Drawing.Size(599, 46);
            this.AppBarCh.TabIndex = 0;
            this.AppBarCh.Title = "Skin Diseases";
            this.AppBarCh.TitleMargin = new System.Windows.Forms.Padding(47, 12, 0, 0);
            this.AppBarCh.IconClick += new System.EventHandler(this.AppBar_IconClick);
            // 
            // pnlContent
            // 
            this.pnlContent.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlContent.AutoScroll = true;
            this.pnlContent.Controls.Add(this.bunifuDropdown3);
            this.pnlContent.Controls.Add(this.bunifuDropdown2);
            this.pnlContent.Controls.Add(this.bunifuDropdown1);
            this.pnlContent.Controls.Add(this.labelC10);
            this.pnlContent.Controls.Add(this.labelC4);
            this.pnlContent.Controls.Add(this.bunifuDropdownC1);
            this.pnlContent.Controls.Add(this.labelC5);
            this.pnlContent.Controls.Add(this.labelC7);
            this.pnlContent.Controls.Add(this.labelS11);
            this.pnlContent.Controls.Add(this.bunifuTextBoxS5);
            this.pnlContent.Controls.Add(this.labelS3);
            this.pnlContent.Controls.Add(this.dtDateS1);
            this.pnlContent.Controls.Add(this.lblCreatedAt);
            this.pnlContent.Controls.Add(this.lblBottom);
            this.pnlContent.Controls.Add(this.btnCancelS1);
            this.pnlContent.Controls.Add(this.btnAddS1);
            themeOption18.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.pnlContent, themeOption18);
            validationObject18.CustomErrorMessage = "";
            validationObject18.Optional = false;
            validationObject18.PropertyName = "Text";
            validationObject18.Regex = null;
            validationObject18.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.pnlContent, validationObject18);
            bindingObject18.Data = "";
            bindingObject18.Property = "Text";
            bindingObject18.TwoWay = true;
            this.bindingProvider.SetLink(this.pnlContent, bindingObject18);
            this.pnlContent.Location = new System.Drawing.Point(0, 52);
            this.pnlContent.Name = "pnlContent";
            this.pnlContent.Size = new System.Drawing.Size(599, 503);
            this.pnlContent.TabIndex = 7;
            this.pnlContent.Paint += new System.Windows.Forms.PaintEventHandler(this.pnlContent_Paint);
            // 
            // bunifuDropdown3
            // 
            this.bunifuDropdown3.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuDropdown3.BackColor = System.Drawing.Color.White;
            this.bunifuDropdown3.BackgroundColor = System.Drawing.Color.White;
            this.bunifuDropdown3.BorderColor = System.Drawing.Color.Silver;
            this.bunifuDropdown3.BorderRadius = 1;
            this.bunifuDropdown3.Color = System.Drawing.Color.Silver;
            this.bunifuDropdown3.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.bunifuDropdown3.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bunifuDropdown3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuDropdown3.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bunifuDropdown3.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.bunifuDropdown3.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.bunifuDropdown3.DisplayMember = "Name";
            this.bunifuDropdown3.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.bunifuDropdown3.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.bunifuDropdown3.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.bunifuDropdown3.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bunifuDropdown3.FillDropDown = true;
            this.bunifuDropdown3.FillIndicator = false;
            this.bunifuDropdown3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bunifuDropdown3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.bunifuDropdown3.ForeColor = System.Drawing.Color.Black;
            this.bunifuDropdown3.Icon = null;
            this.bunifuDropdown3.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bunifuDropdown3.IndicatorColor = System.Drawing.Color.DarkGray;
            this.bunifuDropdown3.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bunifuDropdown3.IndicatorThickness = 2;
            this.bunifuDropdown3.IsDropdownOpened = false;
            this.bunifuDropdown3.ItemBackColor = System.Drawing.Color.White;
            this.bunifuDropdown3.ItemBorderColor = System.Drawing.Color.White;
            this.bunifuDropdown3.ItemForeColor = System.Drawing.Color.Black;
            this.bunifuDropdown3.ItemHeight = 26;
            this.bunifuDropdown3.ItemHighLightColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.bunifuDropdown3.ItemHighLightForeColor = System.Drawing.Color.White;
            this.bunifuDropdown3.Items.AddRange(new object[] {
            "حطاطة",
            "حمامة",
            "لويحة",
            "حويصل",
            "فقاعة",
            "تقرح",
            "عقيدة"});
            this.bunifuDropdown3.ItemTopMargin = 3;
            bindingObject2.Data = "Reason";
            bindingObject2.Property = "Text";
            bindingObject2.TwoWay = true;
            this.bindingProvider.SetLink(this.bunifuDropdown3, bindingObject2);
            validationObject2.CustomErrorMessage = "";
            validationObject2.Optional = false;
            validationObject2.PropertyName = "Text";
            validationObject2.Regex = "";
            validationObject2.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.bunifuDropdown3, validationObject2);
            themeOption2.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.bunifuDropdown3, themeOption2);
            this.bunifuDropdown3.Location = new System.Drawing.Point(12, 184);
            this.bunifuDropdown3.Name = "bunifuDropdown3";
            this.bunifuDropdown3.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.bunifuDropdown3.Size = new System.Drawing.Size(420, 32);
            this.bunifuDropdown3.TabIndex = 48;
            this.bunifuDropdown3.Text = null;
            this.bunifuDropdown3.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bunifuDropdown3.TextLeftMargin = 5;
            this.bunifuDropdown3.ValueMember = "Id";
            // 
            // bunifuDropdown2
            // 
            this.bunifuDropdown2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuDropdown2.BackColor = System.Drawing.Color.White;
            this.bunifuDropdown2.BackgroundColor = System.Drawing.Color.White;
            this.bunifuDropdown2.BorderColor = System.Drawing.Color.Silver;
            this.bunifuDropdown2.BorderRadius = 1;
            this.bunifuDropdown2.Color = System.Drawing.Color.Silver;
            this.bunifuDropdown2.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.bunifuDropdown2.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bunifuDropdown2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuDropdown2.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bunifuDropdown2.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.bunifuDropdown2.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.bunifuDropdown2.DisplayMember = "Name";
            this.bunifuDropdown2.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.bunifuDropdown2.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.bunifuDropdown2.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.bunifuDropdown2.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bunifuDropdown2.FillDropDown = true;
            this.bunifuDropdown2.FillIndicator = false;
            this.bunifuDropdown2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bunifuDropdown2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.bunifuDropdown2.ForeColor = System.Drawing.Color.Black;
            this.bunifuDropdown2.Icon = null;
            this.bunifuDropdown2.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bunifuDropdown2.IndicatorColor = System.Drawing.Color.DarkGray;
            this.bunifuDropdown2.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bunifuDropdown2.IndicatorThickness = 2;
            this.bunifuDropdown2.IsDropdownOpened = false;
            this.bunifuDropdown2.ItemBackColor = System.Drawing.Color.White;
            this.bunifuDropdown2.ItemBorderColor = System.Drawing.Color.White;
            this.bunifuDropdown2.ItemForeColor = System.Drawing.Color.Black;
            this.bunifuDropdown2.ItemHeight = 26;
            this.bunifuDropdown2.ItemHighLightColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.bunifuDropdown2.ItemHighLightForeColor = System.Drawing.Color.White;
            this.bunifuDropdown2.Items.AddRange(new object[] {
            "DiagnosisAr",
            "الكوليرا",
            "الحمى التيفية ونظيرة التيفية وغيرها من الانتانات بالسالمونيلا",
            "الشيغلا",
            "الاميبا الزحارية",
            "انتانات المعدة والامعاء الأخرى وانتانات الكولون غير محددة المصدر",
            "السل",
            "أمراض جرثومية محددة حيوانية المصدر",
            "الكزاز",
            "الانتان بالمكورات السحائية",
            "تجرثم الدم",
            "انتانات تنتقل بالطريق الجنسي بشكل أساسي",
            "انتانات بفيروسات الهربس",
            "جدري الماء",
            "فيروس المنطقة",
            "الحصبة",
            "أمراض فيروسية أخرى تتميز بأفات أغشية مخاطية أو جلدية",
            "التهاب كبد من نمط أ",
            "التهابات الكبد الأخرى",
            "أمراض فيروسية أخرى",
            "الليشمانيا",
            "أمراض طفيلية أخرى",
            "الديدان",
            "القُمال ودَاءُ القَمْل",
            "الجرب",
            "الاحتِشَارات [العَدوى بِالطُّفَيلِيَّات] الأخرى",
            "أمراض جرثومية وانتانية أخرى",
            "خباثات الشفة وجوف الفم والبلعوم",
            "خباثات الكولون والمستقيم والشرج",
            "خباثات الجهاز الهضمي الأخرى",
            "خباثات الرغامى والقصبات والرئة",
            "خباثات الجهالتنفسي والأعضاء داخل الصدر الأخرى",
            "خباثات العظام والغضاريف المفصلية",
            "خباثات الجلد",
            "خباثات الأنسجة الرخوة والمتوسطة",
            "خباثات الثدي",
            "خباثات الجهاز التناسلي الأنثوي",
            "خباثات البروستات",
            "خباثات الجهاز التناسلي الذكري الأخرى",
            "خباثات الجهاز البولي",
            "خباثات العين والدماغ والاجزاء الأخرى من الجهاز العصبي المركزي",
            "خباثات الغدة الدرقية والغدد الصم الأخرى",
            "لمفوما هودجكن و غير هودجكن",
            "اللوكيميا",
            "خباثات أخرى ذات مصدر متعلق بتصنيع الدم والنسيج اللمفي",
            "الأورام السليمة",
            "فقر الدم بنقص الحديد",
            "فقر الدم لاسباب تغذوية أخرى",
            "التلاسيميا",
            "اضطرابات الخلايا المنجلية",
            "فقر الدم الانحلالي لاسباب أخرى",
            "فقر الدم اللامصنع وأنواع فقر الدم الأخرى",
            "عوز العامل الثامن الوراثي",
            "خلل عوامل التخثر الأخرى والفرفريات والاضطرابات النزفية الأخرى",
            "أمراض الدم الأخرى أو الأعضاء المكونة للدم والاضطرابات الأخرى التي تشمل الألية الم" +
                "ناعية",
            "اضطرابات الغدة الدرقية",
            "داء السكري نمط 1",
            "داء السكري نمط 2",
            "أنماط أخرى من السكري",
            "اضطرابات تنظيم الغلوكوز الأخرى والافراز الداخلي للبنكرياس",
            "اضطرابات الغدد الصم الأخرى",
            "سوء التغذية",
            "عوز الأغذية الأخرى",
            "البدانة وفرط التغذية الأخرى",
            "الاضطرابات الاستقلابية",
            "الاضطرابات العقلية العضوية والعرضية",
            "الاضطرابات النفسية والسلوكية الناجمة عن استخدام مواد فعالة نفسيا",
            "اضطرابات الضلالات والفصام",
            "الاضطرابات ثنائية القطبية وما يتعلق بها",
            "اضطرابات الاكتئاب",
            "اضطرابات المزاج الأخرى",
            "العصاب, والاضطرابات الجسمية المرتبطة بالتوتر",
            "متلازمات السلوك المرافقة مع الاضطرابات النفسية والعوامل الفيزيائية",
            "اضطرابات الشخصية والسلوك عند البالغين",
            "التخلف العقلي",
            "اضطرابات التطور النفسية",
            "اضطرابات السلوك والعاطفة التي تبدأ عند الأطفال واليافعين",
            "اضطرابات عقلية غير محددة",
            "الأمراض الالتهابية للجهاز العصبي المركزي",
            "الضمورات الجهازية التي تؤثر بدئيا على الجهاز العصبي المركزي",
            "داء باركنسون",
            "الاضطرابات الحركية وخارج الهرمية الأخرى",
            "الأمراض التنكسية الأخرى للجهاز العصبي",
            "أمراض إزالة النخاع للجهاز العصبي المركزي",
            "الصرع والحالة الصرعية",
            "الشقيقة",
            "متلامات الصداع الأخرى",
            "هجمات الحوادث الاقفارية الدماغية المؤقتة والمتلازمات المتعلقة بها",
            "المتلازمات الوعائية للدماغ في أمراض الأوعية الدماغية (تشمل النشبات الدماغية)",
            "الاضطرابات النوبية والانتيابية الأخرى",
            "اضطرابات الاعصاب والجذور العصبية والضفائر",
            "اعتلال الاعصاب المتعددة والاضطرابات الأخرى للجهاز العصبي المحيطي",
            "اضطرابات الوصل العصبي العضلي والعضلات",
            "الشلل الدماغي والاضطرابات الشللية الأخرى",
            "الاضطرابات العصبية الأخرى",
            "اضطرابات الأجفان والجهاز الدمعي والحجاج",
            "اضطرابات الملتحمة",
            "اضطرابات الصلبة والقرنية والقزحية والجسم الهدبي",
            "اضطرابات العدسة",
            "اضطرابات والمشيمية الشبكية",
            "الزرق",
            "اضطِرابات الجَسم الزُجَاجيّ وكرة العين (المُقلَة)",
            "اضطرابات العصب البصري والسبل البصرية",
            "اضطرابات عضلات العين وحركات العين والمطابقة والانكسار",
            "اضطرابات الرؤية والعمى",
            "الاضطرابات الأخرى للعين وملحقاتها",
            "أمراض الأذن الخارجية",
            "أمراض الأذن الوسطى والخشاء",
            "أمراض الأذن الداخلية",
            "أمراض الأذن الأخرى",
            "الحمى الرثوية الحادة",
            "أمراض القلب الرثوية المزمنة",
            "ارتفاع الضغط البدئي أو الأساسي",
            "أنماط ارتفاع الضغط الأخرى",
            "الذبحة الصدرية",
            "احتشاء العضلة القلبية الحاد",
            "أمراض القلب الاقفارية الأخرى",
            "الداء القلبي الرئوي وأمراض الدوران الرئوي",
            "قصور القلب",
            "أشكال أخرى لأمراض القلب",
            "أمراض الأوعية الدماغية",
            "أمراض الشرايين والشرينات والشعيرات",
            "امراض الأوردة والاوعية اللمفاوية والعقد اللمفاوية غير المصنفة سابقا",
            "اضطرابات جهاز الدوران الأخرى غير المحددة",
            "التهاب البلعوم الأنفي (نزلة البرد)",
            "التهاب الجيوب الحاد",
            "التهاب البلعوم الحاد",
            "التهاب اللوزات الحاد",
            "انتانات الطرق التنفسية العلوية الخرى",
            "الأنفلونزا",
            "ذات الرئة",
            "انتان الطرق التنفسية السفلية الأخرى",
            "الأمراض الأخرى للطرق التنفسية العلوية",
            "مرض الرئة الانسدادي المزمن",
            "الربو والحالة الربوية",
            "توسع القصبات",
            "أمراض الرئة الناجمة عن عوامل خارجية",
            "الأمراض التنفسية الأخرى والتي تصيب النسيج الخلالي",
            "الحالات النخرية والتقيحية للطرق التنفسية السفلية",
            "أمراض الجنب الأخرى",
            "الأمراض الأخرى للجهاز التنفسي",
            "امراض جوف الفم والغد اللعابية والفك",
            "امراض المري والمعدة والاثنى عشري",
            "أمراض الزائدة الدودية",
            "الفتق",
            "التهاب الأمعاء والكولون غير الانتاني",
            "أمراض الأمعاء الأخرى",
            "أمراض البريتوان",
            "أمرراض الكبد",
            "اضطرابات المرارة والطرق الصفراوية والبنكرياس",
            "الأمراض الأخرى للجهاز الهضمي",
            "انتانات الجلد والنسيج تحت الجلد",
            "الاضطرابات الفقاعية",
            "التهاب الادمة والاكزيما",
            "الاضطرابات الحطاطية التوسفية",
            "الحمرة والشرى",
            "الاضطرابات المرتبطة بالأشعة للجلد وتحت الجلد",
            "اضطرابات ملحقات الجلد",
            "الاضطرابات الأخرى للجلد وتحت الجلد",
            "اعتلالات المفاصل",
            "اضطرابات النسيج الضام الجهازية",
            "اعتلالات الظهر",
            "اضطرابات النسج الرخوة",
            "الاعتلالات العظمية والغضروفية",
            "الاضطرابات الأخرى للجهاز العضلي الهيكلي والنسج الضامة",
            "أمراض الكبب",
            "أمراض الكلية الانبويية الخلالية",
            "القصور الكلوي",
            "الحصيات البولية",
            "اضطرابات أخرى في الكلية والحالب",
            "أمراض أخرى للجهاز البولي",
            "امراض الأعضاء التناسلية الذكرية",
            "اضطرابات الثدي",
            "الامراض الالتهابية في الأعضاء الحوضية للانثى",
            "الاضطرابات غير الالتهابية في الطرق التناسلية الأنثوية",
            "اضطرابات أخرى للطرق البولية التناسلية",
            "الحمل مع نتاج اجهاض",
            "ارتفاع الضغط المحرض بالحمل",
            "ما قبل التسمم الحمليّ (الارْتِعاج)",
            "التسمم الحمليّ (الارْتِعاج)",
            "الوذمة والبيلة البروتينية واضطرابات الضغط في الحمل والولادة والنفاس الأخرى",
            "داء السكري أثناء الحمل",
            "أمراض أمومية أخرى متعلقة بشكل أساسي بالحمل",
            "الرعاية بالأم المرتبطة بالجنين والجوف الأمنيوسي ومشاكل الولادة المحتملة",
            "اختلاطات المخاض والولادة",
            "وِلادَة بجنين واحد (مفردة) تلقائيَّة",
            "وِلادَة بجنين واحد (مفردة) بالمِلْقَط وبالمحجم (بالتَخلية)َ (بآلة الشَفط)",
            "ولادة قيصرية",
            "الولادة المساعدة الأخرى لوليد وحيد",
            "الولادة المتعددة",
            "الاختلاطات المتعلقة بشكل أساسي بالنفاس",
            "الحالات الولادية الأخرى غير المصنفة",
            "الجنين أو الوليد المتأثر بعوامل أمومية وباختلاطات الحمل والمخاض والولادة",
            "بطء نمو الجنين وسوء تغذية الأجنة",
            "الاضطرابات المتعلقة بقصر مدة الحمل والمولود ناقص الوزن غير المصنفة في مكان أخر",
            "الاضطرابات المتعلقة بزيادة مدة الحمل و المولود زائد الوزن",
            "رضوض الولادة",
            "الاضطرابات القلبية الوعائية والتنفسية الخاصة بفترة ما حول الولادة",
            "الانتانات الخاصة بفترة ما حول الولادة",
            "الاضطرابات النزفية والدموية للجنين والوليد",
            "الاضطرابات الاستقلابية والصماوية العابرة الخاصة بالجنين و الوليد",
            "اضطرابات الجهاز الهضمي للجنين و الوليد",
            "الحالات التي تنطوي على تكامل وتنظيم درجة حرارة الجنين والوليد",
            "اضطرابات أخرى تنشأ في فترة ما حول الولادة",
            "التشوهات الخلقية للجهاز العصبي",
            "التشوهات الخلقية للعين والأذن والوجه والعنق",
            "تشوهات خلقية في الدورة الدموية",
            "التشوهات الخلقية في الجهاز التنفسي",
            "الشفة المشقوقة والحنك المشقوق",
            "تشوهات خلقية أخرى بالجهاز الهضمي",
            "التشوهات الخلقية للأعضاء التناسلية",
            "تشوهات خلقية في الجهاز البولي",
            "التشوهات الخلقية والتشوهات في الجهاز العضلي الهيكلي",
            "تشوهات خلقية أخرى",
            "تشوهات الصبغيات، غير مصنفة في مكان آخر",
            "الأعراض والعلامات العامة",
            "نتائج غير طبيعية في الفحص ، دون تشخيص",
            "أسباب غير محددة وغير معروفة للوفيات",
            "إصابات الرأس",
            "إصابات العنق",
            "إصابات الصدر",
            "إصابات في البطن وأسفل الظهر والعمود الفقري القطني والحوض",
            "إصابات في الكتف والذراع",
            "إصابات في المرفق والساعد",
            "إصابات في الرسغ واليد",
            "إصابات في الورك والفخذ",
            "إصابات في الركبة والساق",
            "إصابات في الكاحل والقدم",
            "إصابات تشمل مناطق متعددة للجسم",
            "إصابات في جزء غير محدد من منطقة الجذع أو الطرف أو الجسم",
            "الحروق والتآكل",
            "عضة الثلج",
            "التسمم بالعقاقير والأدوية والمواد البيولوجية",
            "الآثار السامة للمواد غير طبية المصدر",
            "آثار أخرى وغير محددة لأسباب خارجية",
            "بعض المضاعفات المبكرة للرضوض",
            "مضاعفات الرعاية الجراحية والطبية ، غير مصنفة في مكان آخر",
            "عقابيل الإصابات والتسمم والنتائج الأخرى لأسباب خارجية",
            "حوادث السير",
            "السقوط",
            "الغرق العرضي والغمر",
            "التعرض للدخان والنيران واللهب",
            "التعرض لقوى الطبيعة",
            "التسمم العرضي والتعرض للمواد الضارة",
            "إيذاء النفس المتعمد",
            "الاعتداءات",
            "الأحداث غير محددة النية",
            "التدخل القانوني وعمليات الحرب",
            "مضاعفات الرعاية الطبية والجراحية",
            "اجراءات منع الحمل",
            "الإشراف على الحمل الطبيعي",
            "الفحص قبل الولادة",
            "ولادة واحدة حية",
            "املاص وحيد",
            "التوأم والحمول المتعددة الأخرى",
            "الرعاية والفحص ما بعد الولادة"});
            this.bunifuDropdown2.ItemTopMargin = 3;
            bindingObject3.Data = "Diagnosis";
            bindingObject3.Property = "Text";
            bindingObject3.TwoWay = true;
            this.bindingProvider.SetLink(this.bunifuDropdown2, bindingObject3);
            validationObject3.CustomErrorMessage = "";
            validationObject3.Optional = false;
            validationObject3.PropertyName = "Text";
            validationObject3.Regex = "";
            validationObject3.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.bunifuDropdown2, validationObject3);
            themeOption3.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.bunifuDropdown2, themeOption3);
            this.bunifuDropdown2.Location = new System.Drawing.Point(12, 240);
            this.bunifuDropdown2.Name = "bunifuDropdown2";
            this.bunifuDropdown2.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.bunifuDropdown2.Size = new System.Drawing.Size(420, 32);
            this.bunifuDropdown2.TabIndex = 47;
            this.bunifuDropdown2.Text = null;
            this.bunifuDropdown2.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bunifuDropdown2.TextLeftMargin = 5;
            this.bunifuDropdown2.ValueMember = "Id";
            // 
            // bunifuDropdown1
            // 
            this.bunifuDropdown1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuDropdown1.BackColor = System.Drawing.Color.White;
            this.bunifuDropdown1.BackgroundColor = System.Drawing.Color.White;
            this.bunifuDropdown1.BorderColor = System.Drawing.Color.Silver;
            this.bunifuDropdown1.BorderRadius = 1;
            this.bunifuDropdown1.Color = System.Drawing.Color.Silver;
            this.bunifuDropdown1.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.bunifuDropdown1.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bunifuDropdown1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuDropdown1.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bunifuDropdown1.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.bunifuDropdown1.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.bunifuDropdown1.DisplayMember = "Name";
            this.bunifuDropdown1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.bunifuDropdown1.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.bunifuDropdown1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.bunifuDropdown1.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bunifuDropdown1.FillDropDown = true;
            this.bunifuDropdown1.FillIndicator = false;
            this.bunifuDropdown1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bunifuDropdown1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.bunifuDropdown1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDropdown1.Icon = null;
            this.bunifuDropdown1.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bunifuDropdown1.IndicatorColor = System.Drawing.Color.DarkGray;
            this.bunifuDropdown1.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bunifuDropdown1.IndicatorThickness = 2;
            this.bunifuDropdown1.IsDropdownOpened = false;
            this.bunifuDropdown1.ItemBackColor = System.Drawing.Color.White;
            this.bunifuDropdown1.ItemBorderColor = System.Drawing.Color.White;
            this.bunifuDropdown1.ItemForeColor = System.Drawing.Color.Black;
            this.bunifuDropdown1.ItemHeight = 26;
            this.bunifuDropdown1.ItemHighLightColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.bunifuDropdown1.ItemHighLightForeColor = System.Drawing.Color.White;
            this.bunifuDropdown1.ItemTopMargin = 3;
            bindingObject4.Data = "DoctorId";
            bindingObject4.Property = "SelectedValue";
            bindingObject4.TwoWay = true;
            this.bindingProvider.SetLink(this.bunifuDropdown1, bindingObject4);
            validationObject4.CustomErrorMessage = "";
            validationObject4.Optional = false;
            validationObject4.PropertyName = "Text";
            validationObject4.Regex = "";
            validationObject4.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.bunifuDropdown1, validationObject4);
            themeOption4.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.bunifuDropdown1, themeOption4);
            this.bunifuDropdown1.Location = new System.Drawing.Point(12, 128);
            this.bunifuDropdown1.Name = "bunifuDropdown1";
            this.bunifuDropdown1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.bunifuDropdown1.Size = new System.Drawing.Size(420, 32);
            this.bunifuDropdown1.TabIndex = 46;
            this.bunifuDropdown1.Text = null;
            this.bunifuDropdown1.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bunifuDropdown1.TextLeftMargin = 5;
            this.bunifuDropdown1.ValueMember = "Id";
            // 
            // labelC10
            // 
            this.labelC10.AutoSize = true;
            this.labelC10.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            bindingObject5.Data = "";
            bindingObject5.Property = "Text";
            bindingObject5.TwoWay = true;
            this.bindingProvider.SetLink(this.labelC10, bindingObject5);
            themeOption5.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.labelC10, themeOption5);
            validationObject5.CustomErrorMessage = "";
            validationObject5.Optional = false;
            validationObject5.PropertyName = "Text";
            validationObject5.Regex = null;
            validationObject5.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.labelC10, validationObject5);
            this.labelC10.Location = new System.Drawing.Point(507, 249);
            this.labelC10.Name = "labelC10";
            this.labelC10.Size = new System.Drawing.Size(46, 15);
            this.labelC10.TabIndex = 45;
            this.labelC10.Text = "التشخيص";
            // 
            // labelC4
            // 
            this.labelC4.AutoSize = true;
            this.labelC4.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            bindingObject6.Data = "";
            bindingObject6.Property = "Text";
            bindingObject6.TwoWay = true;
            this.bindingProvider.SetLink(this.labelC4, bindingObject6);
            themeOption6.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.labelC4, themeOption6);
            validationObject6.CustomErrorMessage = "";
            validationObject6.Optional = false;
            validationObject6.PropertyName = "Text";
            validationObject6.Regex = null;
            validationObject6.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.labelC4, validationObject6);
            this.labelC4.Location = new System.Drawing.Point(494, 81);
            this.labelC4.Name = "labelC4";
            this.labelC4.Size = new System.Drawing.Size(72, 15);
            this.labelC4.TabIndex = 42;
            this.labelC4.Text = "نوع مقدم الخدمة";
            // 
            // bunifuDropdownC1
            // 
            this.bunifuDropdownC1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuDropdownC1.BackColor = System.Drawing.Color.White;
            this.bunifuDropdownC1.BackgroundColor = System.Drawing.Color.White;
            this.bunifuDropdownC1.BorderColor = System.Drawing.Color.Silver;
            this.bunifuDropdownC1.BorderRadius = 1;
            this.bunifuDropdownC1.Color = System.Drawing.Color.Silver;
            this.bunifuDropdownC1.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.bunifuDropdownC1.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bunifuDropdownC1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuDropdownC1.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.bunifuDropdownC1.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.bunifuDropdownC1.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.bunifuDropdownC1.DisplayMember = "Name";
            this.bunifuDropdownC1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.bunifuDropdownC1.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.bunifuDropdownC1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.bunifuDropdownC1.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bunifuDropdownC1.FillDropDown = true;
            this.bunifuDropdownC1.FillIndicator = false;
            this.bunifuDropdownC1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.bunifuDropdownC1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.bunifuDropdownC1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDropdownC1.Icon = null;
            this.bunifuDropdownC1.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bunifuDropdownC1.IndicatorColor = System.Drawing.Color.DarkGray;
            this.bunifuDropdownC1.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.bunifuDropdownC1.IndicatorThickness = 2;
            this.bunifuDropdownC1.IsDropdownOpened = false;
            this.bunifuDropdownC1.ItemBackColor = System.Drawing.Color.White;
            this.bunifuDropdownC1.ItemBorderColor = System.Drawing.Color.White;
            this.bunifuDropdownC1.ItemForeColor = System.Drawing.Color.Black;
            this.bunifuDropdownC1.ItemHeight = 26;
            this.bunifuDropdownC1.ItemHighLightColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.bunifuDropdownC1.ItemHighLightForeColor = System.Drawing.Color.White;
            this.bunifuDropdownC1.Items.AddRange(new object[] {
            "طبيب",
            "ممرض",
            "قابلة",
            "فني"});
            this.bunifuDropdownC1.ItemTopMargin = 3;
            bindingObject7.Data = "TSerProvide";
            bindingObject7.Property = "Text";
            bindingObject7.TwoWay = true;
            this.bindingProvider.SetLink(this.bunifuDropdownC1, bindingObject7);
            validationObject7.CustomErrorMessage = "";
            validationObject7.Optional = false;
            validationObject7.PropertyName = "Text";
            validationObject7.Regex = "";
            validationObject7.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.bunifuDropdownC1, validationObject7);
            themeOption7.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.bunifuDropdownC1, themeOption7);
            this.bunifuDropdownC1.Location = new System.Drawing.Point(12, 72);
            this.bunifuDropdownC1.Name = "bunifuDropdownC1";
            this.bunifuDropdownC1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.bunifuDropdownC1.Size = new System.Drawing.Size(420, 32);
            this.bunifuDropdownC1.TabIndex = 40;
            this.bunifuDropdownC1.Text = null;
            this.bunifuDropdownC1.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.bunifuDropdownC1.TextLeftMargin = 5;
            this.bunifuDropdownC1.ValueMember = "Id";
            // 
            // labelC5
            // 
            this.labelC5.AutoSize = true;
            this.labelC5.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            bindingObject8.Data = "";
            bindingObject8.Property = "Text";
            bindingObject8.TwoWay = true;
            this.bindingProvider.SetLink(this.labelC5, bindingObject8);
            themeOption8.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.labelC5, themeOption8);
            validationObject8.CustomErrorMessage = "";
            validationObject8.Optional = false;
            validationObject8.PropertyName = "Text";
            validationObject8.Regex = null;
            validationObject8.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.labelC5, validationObject8);
            this.labelC5.Location = new System.Drawing.Point(495, 137);
            this.labelC5.Name = "labelC5";
            this.labelC5.Size = new System.Drawing.Size(71, 15);
            this.labelC5.TabIndex = 43;
            this.labelC5.Text = "اسم مقدم الخدمة";
            // 
            // labelC7
            // 
            this.labelC7.AutoSize = true;
            this.labelC7.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            bindingObject9.Data = "";
            bindingObject9.Property = "Text";
            bindingObject9.TwoWay = true;
            this.bindingProvider.SetLink(this.labelC7, bindingObject9);
            themeOption9.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.labelC7, themeOption9);
            validationObject9.CustomErrorMessage = "";
            validationObject9.Optional = false;
            validationObject9.PropertyName = "Text";
            validationObject9.Regex = null;
            validationObject9.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.labelC7, validationObject9);
            this.labelC7.Location = new System.Drawing.Point(511, 193);
            this.labelC7.Name = "labelC7";
            this.labelC7.Size = new System.Drawing.Size(38, 15);
            this.labelC7.TabIndex = 44;
            this.labelC7.Text = "الشكوى";
            // 
            // labelS11
            // 
            this.labelS11.AutoSize = true;
            this.labelS11.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            bindingObject10.Data = "";
            bindingObject10.Property = "Text";
            bindingObject10.TwoWay = true;
            this.bindingProvider.SetLink(this.labelS11, bindingObject10);
            themeOption10.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.labelS11, themeOption10);
            validationObject10.CustomErrorMessage = "";
            validationObject10.Optional = false;
            validationObject10.PropertyName = "Text";
            validationObject10.Regex = null;
            validationObject10.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.labelS11, validationObject10);
            this.labelS11.Location = new System.Drawing.Point(481, 305);
            this.labelS11.Name = "labelS11";
            this.labelS11.Size = new System.Drawing.Size(99, 15);
            this.labelS11.TabIndex = 30;
            this.labelS11.Text = "الأدوية التي تم إعطاؤها";
            // 
            // bunifuTextBoxS5
            // 
            this.bunifuTextBoxS5.AcceptsReturn = false;
            this.bunifuTextBoxS5.AcceptsTab = false;
            this.bunifuTextBoxS5.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuTextBoxS5.AnimationSpeed = 200;
            this.bunifuTextBoxS5.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxS5.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxS5.AutoSizeHeight = true;
            this.bunifuTextBoxS5.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxS5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxS5.BackgroundImage")));
            this.bunifuTextBoxS5.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.bunifuTextBoxS5.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxS5.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(150)))), ((int)(((byte)(140)))));
            this.bunifuTextBoxS5.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxS5.BorderRadius = 1;
            this.bunifuTextBoxS5.BorderThickness = 1;
            this.bunifuTextBoxS5.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxS5.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxS5.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuTextBoxS5.DefaultText = "";
            this.bunifuTextBoxS5.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxS5.HideSelection = true;
            this.bunifuTextBoxS5.IconLeft = null;
            this.bunifuTextBoxS5.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxS5.IconPadding = 10;
            this.bunifuTextBoxS5.IconRight = null;
            this.bunifuTextBoxS5.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxS5.Lines = new string[0];
            bindingObject11.Data = "Medicine";
            bindingObject11.Property = "Text";
            bindingObject11.TwoWay = true;
            this.bindingProvider.SetLink(this.bunifuTextBoxS5, bindingObject11);
            themeOption11.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.bunifuTextBoxS5, themeOption11);
            validationObject11.CustomErrorMessage = "";
            validationObject11.Optional = false;
            validationObject11.PropertyName = "Text";
            validationObject11.Regex = "(.|\\s)*\\S(.|\\s)*";
            validationObject11.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.bunifuTextBoxS5, validationObject11);
            this.bunifuTextBoxS5.Location = new System.Drawing.Point(12, 296);
            this.bunifuTextBoxS5.MaxLength = 32767;
            this.bunifuTextBoxS5.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxS5.Modified = false;
            this.bunifuTextBoxS5.Multiline = true;
            this.bunifuTextBoxS5.Name = "bunifuTextBoxS5";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxS5.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxS5.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(150)))), ((int)(((byte)(140)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxS5.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxS5.OnIdleState = stateProperties4;
            this.bunifuTextBoxS5.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxS5.PasswordChar = '\0';
            this.bunifuTextBoxS5.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxS5.PlaceholderText = "";
            this.bunifuTextBoxS5.ReadOnly = false;
            this.bunifuTextBoxS5.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.bunifuTextBoxS5.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxS5.SelectedText = "";
            this.bunifuTextBoxS5.SelectionLength = 0;
            this.bunifuTextBoxS5.SelectionStart = 0;
            this.bunifuTextBoxS5.ShortcutsEnabled = true;
            this.bunifuTextBoxS5.Size = new System.Drawing.Size(420, 32);
            this.bunifuTextBoxS5.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBoxS5.TabIndex = 13;
            this.bunifuTextBoxS5.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            this.bunifuTextBoxS5.TextMarginBottom = 0;
            this.bunifuTextBoxS5.TextMarginLeft = 1;
            this.bunifuTextBoxS5.TextMarginTop = 1;
            this.bunifuTextBoxS5.TextPlaceholder = "";
            this.bunifuTextBoxS5.UseSystemPasswordChar = false;
            this.bunifuTextBoxS5.WordWrap = true;
            // 
            // labelS3
            // 
            this.labelS3.AutoSize = true;
            this.labelS3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            bindingObject12.Data = "";
            bindingObject12.Property = "Text";
            bindingObject12.TwoWay = true;
            this.bindingProvider.SetLink(this.labelS3, bindingObject12);
            themeOption12.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.labelS3, themeOption12);
            validationObject12.CustomErrorMessage = "";
            validationObject12.Optional = false;
            validationObject12.PropertyName = "Text";
            validationObject12.Regex = null;
            validationObject12.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.labelS3, validationObject12);
            this.labelS3.Location = new System.Drawing.Point(498, 25);
            this.labelS3.Name = "labelS3";
            this.labelS3.Size = new System.Drawing.Size(65, 15);
            this.labelS3.TabIndex = 2;
            this.labelS3.Text = "تاريخ الزيارة*";
            this.labelS3.Click += new System.EventHandler(this.lblDate_Click);
            // 
            // dtDateS1
            // 
            this.dtDateS1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dtDateS1.BackColor = System.Drawing.Color.White;
            this.dtDateS1.BorderColor = System.Drawing.Color.Silver;
            this.dtDateS1.BorderRadius = 1;
            this.dtDateS1.CalendarMonthBackground = System.Drawing.Color.White;
            this.dtDateS1.CalendarTitleBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.dtDateS1.CalendarTitleForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.dtDateS1.CalendarTrailingForeColor = System.Drawing.Color.Gray;
            this.dtDateS1.Color = System.Drawing.Color.Silver;
            this.dtDateS1.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtDateS1.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtDateS1.DisabledColor = System.Drawing.Color.Gray;
            this.dtDateS1.DisplayWeekNumbers = false;
            this.dtDateS1.DPHeight = 0;
            this.dtDateS1.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtDateS1.FillDatePicker = false;
            this.dtDateS1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.dtDateS1.ForeColor = System.Drawing.Color.Black;
            this.dtDateS1.Icon = ((System.Drawing.Image)(resources.GetObject("dtDateS1.Icon")));
            this.dtDateS1.IconColor = System.Drawing.Color.Gray;
            this.dtDateS1.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtDateS1.LeftTextMargin = 5;
            bindingObject13.Data = "Visit_Date";
            bindingObject13.Property = "Value";
            bindingObject13.TwoWay = true;
            this.bindingProvider.SetLink(this.dtDateS1, bindingObject13);
            themeOption13.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.dtDateS1, themeOption13);
            validationObject13.CustomErrorMessage = "";
            validationObject13.Optional = false;
            validationObject13.PropertyName = "Value";
            validationObject13.Regex = "";
            validationObject13.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.dtDateS1, validationObject13);
            this.dtDateS1.Location = new System.Drawing.Point(12, 16);
            this.dtDateS1.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtDateS1.Name = "dtDateS1";
            this.dtDateS1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.dtDateS1.Size = new System.Drawing.Size(420, 32);
            this.dtDateS1.TabIndex = 3;
            this.dtDateS1.ValueChanged += new System.EventHandler(this.dtDate_ValueChanged);
            // 
            // lblCreatedAt
            // 
            this.lblCreatedAt.AutoSize = true;
            this.lblCreatedAt.ForeColor = System.Drawing.Color.Transparent;
            bindingObject14.Data = "";
            bindingObject14.Property = "Text";
            bindingObject14.TwoWay = true;
            this.bindingProvider.SetLink(this.lblCreatedAt, bindingObject14);
            themeOption14.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblCreatedAt, themeOption14);
            validationObject14.CustomErrorMessage = "";
            validationObject14.Optional = false;
            validationObject14.PropertyName = "Text";
            validationObject14.Regex = null;
            validationObject14.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblCreatedAt, validationObject14);
            this.lblCreatedAt.Location = new System.Drawing.Point(500, 468);
            this.lblCreatedAt.Name = "lblCreatedAt";
            this.lblCreatedAt.Size = new System.Drawing.Size(62, 15);
            this.lblCreatedAt.TabIndex = 27;
            this.lblCreatedAt.Text = "Created At";
            this.lblCreatedAt.Click += new System.EventHandler(this.lblCreatedAt_Click);
            // 
            // lblBottom
            // 
            this.lblBottom.AutoSize = true;
            bindingObject15.Data = "";
            bindingObject15.Property = "Text";
            bindingObject15.TwoWay = true;
            this.bindingProvider.SetLink(this.lblBottom, bindingObject15);
            themeOption15.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblBottom, themeOption15);
            validationObject15.CustomErrorMessage = "";
            validationObject15.Optional = false;
            validationObject15.PropertyName = "Text";
            validationObject15.Regex = null;
            validationObject15.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblBottom, validationObject15);
            this.lblBottom.Location = new System.Drawing.Point(16, 726);
            this.lblBottom.Name = "lblBottom";
            this.lblBottom.Size = new System.Drawing.Size(0, 15);
            this.lblBottom.TabIndex = 28;
            this.lblBottom.Click += new System.EventHandler(this.lblBottom_Click);
            // 
            // btnCancelS1
            // 
            this.btnCancelS1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCancelS1.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.btnCancelS1.FlatAppearance.BorderSize = 2;
            this.btnCancelS1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCancelS1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancelS1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            bindingObject16.Data = "";
            bindingObject16.Property = "Text";
            bindingObject16.TwoWay = true;
            this.bindingProvider.SetLink(this.btnCancelS1, bindingObject16);
            themeOption16.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.btnCancelS1, themeOption16);
            validationObject16.CustomErrorMessage = "";
            validationObject16.Optional = false;
            validationObject16.PropertyName = "Text";
            validationObject16.Regex = null;
            validationObject16.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.btnCancelS1, validationObject16);
            this.btnCancelS1.Location = new System.Drawing.Point(381, 399);
            this.btnCancelS1.Name = "btnCancelS1";
            this.btnCancelS1.Size = new System.Drawing.Size(92, 40);
            this.btnCancelS1.TabIndex = 13;
            this.btnCancelS1.Text = "إنهاء";
            this.btnCancelS1.UseVisualStyleBackColor = false;
            this.btnCancelS1.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnAddS1
            // 
            this.btnAddS1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAddS1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(42)))), ((int)(((byte)(43)))));
            this.btnAddS1.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.btnAddS1.FlatAppearance.BorderSize = 2;
            this.btnAddS1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAddS1.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddS1.ForeColor = System.Drawing.Color.White;
            bindingObject17.Data = "";
            bindingObject17.Property = "Text";
            bindingObject17.TwoWay = true;
            this.bindingProvider.SetLink(this.btnAddS1, bindingObject17);
            themeOption17.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.btnAddS1, themeOption17);
            validationObject17.CustomErrorMessage = "";
            validationObject17.Optional = false;
            validationObject17.PropertyName = "Text";
            validationObject17.Regex = null;
            validationObject17.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.btnAddS1, validationObject17);
            this.btnAddS1.Location = new System.Drawing.Point(479, 399);
            this.btnAddS1.Name = "btnAddS1";
            this.btnAddS1.Size = new System.Drawing.Size(92, 40);
            this.btnAddS1.TabIndex = 12;
            this.btnAddS1.Text = "حفظ";
            this.btnAddS1.UseVisualStyleBackColor = false;
            this.btnAddS1.Click += new System.EventHandler(this.btnAdd_Click);
            // 
            // bunifuFormDock
            // 
            this.bunifuFormDock.AllowFormDragging = true;
            this.bunifuFormDock.AllowFormDropShadow = true;
            this.bunifuFormDock.AllowFormResizing = true;
            this.bunifuFormDock.AllowHidingBottomRegion = true;
            this.bunifuFormDock.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock.ContainerControl = this;
            this.bunifuFormDock.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock.DockingOptions.DockAll = true;
            this.bunifuFormDock.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock.DockingOptions.DockLeft = true;
            this.bunifuFormDock.DockingOptions.DockRight = true;
            this.bunifuFormDock.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock.DockingOptions.DockTopRight = true;
            this.bunifuFormDock.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock.ParentForm = this;
            this.bunifuFormDock.ShowCursorChanges = true;
            this.bunifuFormDock.ShowDockingIndicators = false;
            this.bunifuFormDock.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock.TitleBarOptions.BunifuFormDock = this.bunifuFormDock;
            this.bunifuFormDock.TitleBarOptions.DoubleClickToExpandWindow = false;
            this.bunifuFormDock.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            this.bunifuFormDock.FormDragging += new System.EventHandler<Bunifu.UI.WinForms.BunifuFormDock.FormDraggingEventArgs>(this.bunifuFormDock_FormDragging);
            // 
            // openFileDialog
            // 
            this.openFileDialog.FileOk += new System.ComponentModel.CancelEventHandler(this.openFileDialog_FileOk);
            // 
            // saveFileDialog
            // 
            this.saveFileDialog.FileOk += new System.ComponentModel.CancelEventHandler(this.saveFileDialog_FileOk);
            // 
            // Skin
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.WhiteSmoke;
            this.ClientSize = new System.Drawing.Size(599, 567);
            this.Controls.Add(this.pnlContent);
            this.Controls.Add(this.AppBarCh);
            this.DoubleBuffered = true;
            this.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.MaximizeBox = false;
            this.Name = "Skin";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Frm_Visit";
            this.Load += new System.EventHandler(this.Frm_Load);
            this.pnlContent.ResumeLayout(false);
            this.pnlContent.PerformLayout();
            this.ResumeLayout(false);

        }

        #region  Jenga Generated Code
        public void JengaInit(Color themeColor)
        {
            AppBarCh.BackColor = themeColor;
            foreach (Control ctrl in pnlContent.Controls)
            {
                if (ctrl.GetType() == typeof(Bunifu.UI.WinForms.BunifuTextBox))
                {
                    var ctr = (Bunifu.UI.WinForms.BunifuTextBox)ctrl;
                    ctr.OnHoverState.BorderColor
                        = ctr.OnActiveState.BorderColor
                        = themeColor;

                }
                else if (ctrl.GetType() == typeof(Bunifu.UI.WinForms.BunifuDropdown))
                {
                    var ctr = (Bunifu.UI.WinForms.BunifuDropdown)ctrl;
                    ctr.ItemHighLightColor = themeColor;
                    ctr.ItemHighLightForeColor = Color.White;
                }
                else if (ctrl.GetType() == typeof(LinkLabel))
                {
                    var ctr = (LinkLabel)ctrl;
                    ctr.LinkColor
                        = ctr.VisitedLinkColor
                        = themeColor;
                }
                else if (ctrl.GetType() == typeof(Button))
                {
                    var ctr = (Button)ctrl;
                    ctr.FlatAppearance.BorderColor = themeColor;

                    if (ctr.Name == "btnAdd")
                        ctr.BackColor = themeColor;
                    else
                        ctr.ForeColor = themeColor;
                }
                else if (ctrl.GetType() == typeof(Bunifu.UI.WinForms.BunifuCheckBox))
                {
                    var ctr = (Bunifu.UI.WinForms.BunifuCheckBox)ctrl;
                    ctr.OnCheck.BorderColor = themeColor;
                    ctr.OnCheck.CheckBoxColor = themeColor;

                    ctr.OnUncheck.BorderColor = themeColor;
                    ctr.OnUncheck.CheckBoxColor = Color.WhiteSmoke;

                }

            }
        }
        #endregion

        #endregion
        public Kimtoo.ValidationProvider.ValidationProvider validationProvider;
        public Kimtoo.BindingProvider.BindingProvider bindingProvider;
        public Kimtoo.ThemeProvider.ThemeProvider themeProvider;
        public System.Windows.Forms.Button btnAddS1;
        public System.Windows.Forms.Button btnCancelS1;
        public Bunifu.Utils.BunifuAppBar AppBarCh;
        public System.Windows.Forms.Panel pnlContent;
        public Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock;
        public Bunifu.UI.WinForms.BunifuSnackbar Alert;
        public System.Windows.Forms.OpenFileDialog openFileDialog;
        public System.Windows.Forms.SaveFileDialog saveFileDialog;
        public System.Windows.Forms.Label labelS3;
        public Bunifu.UI.WinForms.BunifuDatePicker dtDateS1;
        public System.Windows.Forms.Label lblBottom;
        public Label lblCreatedAt;
        public Label labelS11;
        public Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxS5;
        public Bunifu.UI.WinForms.BunifuDropdown bunifuDropdown2;
        public Bunifu.UI.WinForms.BunifuDropdown bunifuDropdown1;
        public Label labelC10;
        public Label labelC4;
        public Bunifu.UI.WinForms.BunifuDropdown bunifuDropdownC1;
        public Label labelC5;
        public Bunifu.UI.WinForms.BunifuDropdown bunifuDropdown3;
        public Label labelC7;
        //declare
    }
}