//Code Generated by Jenga.NET 
            using System.Drawing;
            using System.Windows.Forms;

			namespace PatientRecordManagement.Dialogs
			{
			partial class Frm_Doctor
			{

			private System.ComponentModel.IContainer components = null;

			protected override void Dispose(bool disposing)
			{
			if (disposing && (components != null))
			{
			components.Dispose();
			}
			base.Dispose(disposing);
			}

			#region Windows Form Designer generated code

			private void InitializeComponent()
			{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Frm_Doctor));
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject1 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption1 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject1 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption21 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject21 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject21 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject4 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption4 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject4 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject5 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption5 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject5 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject6 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption6 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject6 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject7 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ValidationProvider.ValidationObject validationObject7 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption7 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject8 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption8 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject8 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject9 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption9 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject9 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject10 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption10 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject10 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject11 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption11 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject11 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject12 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption12 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject12 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject13 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption13 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject13 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject14 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption14 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject14 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject15 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption15 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject15 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject16 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption16 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject16 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject17 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption17 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject17 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject18 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption18 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject18 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject19 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption19 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject19 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject20 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption20 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject20 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject2 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption2 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject2 = new Kimtoo.ValidationProvider.ValidationObject();
            Kimtoo.BindingProvider.BindingProvider.BindingObject bindingObject3 = new Kimtoo.BindingProvider.BindingProvider.BindingObject();
            Kimtoo.ThemeProvider.ThemeProvider.ThemeOption themeOption3 = new Kimtoo.ThemeProvider.ThemeProvider.ThemeOption();
            Kimtoo.ValidationProvider.ValidationObject validationObject3 = new Kimtoo.ValidationProvider.ValidationObject();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.Alert = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.validationProvider = new Kimtoo.ValidationProvider.ValidationProvider();
            this.AppBar = new Bunifu.Utils.BunifuAppBar();
            this.pnlContent = new System.Windows.Forms.Panel();
            this.lblName = new System.Windows.Forms.Label();
            this.txtName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblGender = new System.Windows.Forms.Label();
            this.cmbGender = new Bunifu.UI.WinForms.BunifuDropdown();
            this.lblDOB = new System.Windows.Forms.Label();
            this.dtDOB = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.lblPhone = new System.Windows.Forms.Label();
            this.txtPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblEmail = new System.Windows.Forms.Label();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblDateJoined = new System.Windows.Forms.Label();
            this.dtDateJoined = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.lblNotes = new System.Windows.Forms.Label();
            this.txtNotes = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblBottom = new System.Windows.Forms.Label();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnAdd = new System.Windows.Forms.Button();
            this.bindingProvider = new Kimtoo.BindingProvider.BindingProvider();
            this.themeProvider = new Kimtoo.ThemeProvider.ThemeProvider();
            this.bunifuFormDock = new Bunifu.UI.WinForms.BunifuFormDock();
            this.openFileDialog = new System.Windows.Forms.OpenFileDialog();
            this.saveFileDialog = new System.Windows.Forms.SaveFileDialog();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pnlContent.SuspendLayout();
            this.SuspendLayout();
            // 
            // Alert
            // 
            this.Alert.AllowDragging = false;
            this.Alert.AllowMultipleViews = true;
            this.Alert.ClickToClose = true;
            this.Alert.DoubleClickToClose = true;
            this.Alert.DurationAfterIdle = 3000;
            this.Alert.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.ErrorOptions.ActionBorderRadius = 1;
            this.Alert.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Alert.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Alert.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.Alert.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.Alert.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.Alert.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Alert.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.Alert.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.Alert.ErrorOptions.IconLeftMargin = 12;
            this.Alert.FadeCloseIcon = false;
            this.Alert.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.Alert.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.InformationOptions.ActionBorderRadius = 1;
            this.Alert.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Alert.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Alert.InformationOptions.BackColor = System.Drawing.Color.White;
            this.Alert.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.Alert.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.Alert.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Alert.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.Alert.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.Alert.InformationOptions.IconLeftMargin = 12;
            this.Alert.Margin = 10;
            this.Alert.MaximumSize = new System.Drawing.Size(0, 0);
            this.Alert.MaximumViews = 7;
            this.Alert.MessageRightMargin = 15;
            this.Alert.MinimumSize = new System.Drawing.Size(0, 0);
            this.Alert.ShowBorders = false;
            this.Alert.ShowCloseIcon = false;
            this.Alert.ShowIcon = true;
            this.Alert.ShowShadows = true;
            this.Alert.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.SuccessOptions.ActionBorderRadius = 1;
            this.Alert.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Alert.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Alert.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.Alert.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.Alert.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.Alert.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Alert.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.Alert.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.Alert.SuccessOptions.IconLeftMargin = 12;
            this.Alert.ViewsMargin = 7;
            this.Alert.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Alert.WarningOptions.ActionBorderRadius = 1;
            this.Alert.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Alert.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Alert.WarningOptions.BackColor = System.Drawing.Color.White;
            this.Alert.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.Alert.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.Alert.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Alert.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.Alert.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.Alert.WarningOptions.IconLeftMargin = 12;
            this.Alert.ZoomCloseIcon = true;
            // 
            // validationProvider
            // 
            this.validationProvider.ErrorColor = System.Drawing.Color.Crimson;
            // 
            // AppBar
            // 
            this.AppBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.AppBar.ControlBoxColor = System.Drawing.Color.WhiteSmoke;
            this.AppBar.ControlBoxColorActive = System.Drawing.Color.White;
            this.AppBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.AppBar.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold);
            this.AppBar.ForeColor = System.Drawing.Color.White;
            this.AppBar.Icon = ((System.Drawing.Image)(resources.GetObject("AppBar.Icon")));
            bindingObject1.Data = "";
            bindingObject1.Property = "Text";
            bindingObject1.TwoWay = true;
            this.bindingProvider.SetLink(this.AppBar, bindingObject1);
            themeOption1.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.AppBar, themeOption1);
            validationObject1.CustomErrorMessage = "";
            validationObject1.Optional = false;
            validationObject1.PropertyName = "Text";
            validationObject1.Regex = null;
            validationObject1.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.AppBar, validationObject1);
            this.AppBar.Location = new System.Drawing.Point(0, 0);
            this.AppBar.Name = "AppBar";
            this.AppBar.Size = new System.Drawing.Size(599, 46);
            this.AppBar.TabIndex = 6;
            this.AppBar.Title = "Doctor";
            this.AppBar.TitleMargin = new System.Windows.Forms.Padding(47, 12, 0, 0);
            // 
            // pnlContent
            // 
            this.pnlContent.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pnlContent.AutoScroll = true;
            this.pnlContent.Controls.Add(this.label1);
            this.pnlContent.Controls.Add(this.bunifuTextBox1);
            this.pnlContent.Controls.Add(this.lblName);
            this.pnlContent.Controls.Add(this.txtName);
            this.pnlContent.Controls.Add(this.lblGender);
            this.pnlContent.Controls.Add(this.cmbGender);
            this.pnlContent.Controls.Add(this.lblDOB);
            this.pnlContent.Controls.Add(this.dtDOB);
            this.pnlContent.Controls.Add(this.lblPhone);
            this.pnlContent.Controls.Add(this.txtPhone);
            this.pnlContent.Controls.Add(this.lblEmail);
            this.pnlContent.Controls.Add(this.txtEmail);
            this.pnlContent.Controls.Add(this.lblDateJoined);
            this.pnlContent.Controls.Add(this.dtDateJoined);
            this.pnlContent.Controls.Add(this.lblNotes);
            this.pnlContent.Controls.Add(this.txtNotes);
            this.pnlContent.Controls.Add(this.lblBottom);
            this.pnlContent.Controls.Add(this.btnCancel);
            this.pnlContent.Controls.Add(this.btnAdd);
            themeOption21.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.pnlContent, themeOption21);
            validationObject21.CustomErrorMessage = "";
            validationObject21.Optional = false;
            validationObject21.PropertyName = "Text";
            validationObject21.Regex = null;
            validationObject21.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.pnlContent, validationObject21);
            bindingObject21.Data = "";
            bindingObject21.Property = "Text";
            bindingObject21.TwoWay = true;
            this.bindingProvider.SetLink(this.pnlContent, bindingObject21);
            this.pnlContent.Location = new System.Drawing.Point(3, 51);
            this.pnlContent.Name = "pnlContent";
            this.pnlContent.Size = new System.Drawing.Size(590, 515);
            this.pnlContent.TabIndex = 7;
            // 
            // lblName
            // 
            this.lblName.AutoSize = true;
            this.lblName.Font = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            bindingObject4.Data = "";
            bindingObject4.Property = "Text";
            bindingObject4.TwoWay = true;
            this.bindingProvider.SetLink(this.lblName, bindingObject4);
            themeOption4.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblName, themeOption4);
            validationObject4.CustomErrorMessage = "";
            validationObject4.Optional = false;
            validationObject4.PropertyName = "Text";
            validationObject4.Regex = null;
            validationObject4.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblName, validationObject4);
            this.lblName.Location = new System.Drawing.Point(494, 25);
            this.lblName.Name = "lblName";
            this.lblName.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblName.Size = new System.Drawing.Size(40, 22);
            this.lblName.TabIndex = 4;
            this.lblName.Text = "الاسم";
            // 
            // txtName
            // 
            this.txtName.AcceptsReturn = false;
            this.txtName.AcceptsTab = false;
            this.txtName.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtName.AnimationSpeed = 200;
            this.txtName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtName.AutoSizeHeight = true;
            this.txtName.BackColor = System.Drawing.Color.White;
            this.txtName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtName.BackgroundImage")));
            this.txtName.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.txtName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.txtName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtName.BorderRadius = 1;
            this.txtName.BorderThickness = 1;
            this.txtName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.DefaultFont = new System.Drawing.Font("Droid Arabic Kufi", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtName.DefaultText = "";
            this.txtName.FillColor = System.Drawing.Color.White;
            this.txtName.HideSelection = true;
            this.txtName.IconLeft = null;
            this.txtName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.IconPadding = 10;
            this.txtName.IconRight = null;
            this.txtName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.Lines = new string[0];
            bindingObject5.Data = "Name";
            bindingObject5.Property = "Text";
            bindingObject5.TwoWay = true;
            this.bindingProvider.SetLink(this.txtName, bindingObject5);
            themeOption5.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.txtName, themeOption5);
            validationObject5.CustomErrorMessage = "";
            validationObject5.Optional = false;
            validationObject5.PropertyName = "Text";
            validationObject5.Regex = "^[a-z ,.\'-]+$";
            validationObject5.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.txtName, validationObject5);
            this.txtName.Location = new System.Drawing.Point(33, 25);
            this.txtName.MaxLength = 32767;
            this.txtName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtName.Modified = false;
            this.txtName.Multiline = false;
            this.txtName.Name = "txtName";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnIdleState = stateProperties8;
            this.txtName.Padding = new System.Windows.Forms.Padding(3);
            this.txtName.PasswordChar = '\0';
            this.txtName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtName.PlaceholderText = "";
            this.txtName.ReadOnly = false;
            this.txtName.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.txtName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtName.SelectedText = "";
            this.txtName.SelectionLength = 0;
            this.txtName.SelectionStart = 0;
            this.txtName.ShortcutsEnabled = true;
            this.txtName.Size = new System.Drawing.Size(389, 45);
            this.txtName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtName.TabIndex = 1;
            this.txtName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtName.TextMarginBottom = 0;
            this.txtName.TextMarginLeft = 3;
            this.txtName.TextMarginTop = 1;
            this.txtName.TextPlaceholder = "";
            this.txtName.UseSystemPasswordChar = false;
            this.txtName.WordWrap = true;
            // 
            // lblGender
            // 
            this.lblGender.AutoSize = true;
            this.lblGender.Font = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            bindingObject6.Data = "";
            bindingObject6.Property = "Text";
            bindingObject6.TwoWay = true;
            this.bindingProvider.SetLink(this.lblGender, bindingObject6);
            themeOption6.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblGender, themeOption6);
            validationObject6.CustomErrorMessage = "";
            validationObject6.Optional = false;
            validationObject6.PropertyName = "Text";
            validationObject6.Regex = null;
            validationObject6.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblGender, validationObject6);
            this.lblGender.Location = new System.Drawing.Point(491, 92);
            this.lblGender.Name = "lblGender";
            this.lblGender.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblGender.Size = new System.Drawing.Size(43, 22);
            this.lblGender.TabIndex = 6;
            this.lblGender.Text = "الجنس";
            // 
            // cmbGender
            // 
            this.cmbGender.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.cmbGender.BackColor = System.Drawing.Color.White;
            this.cmbGender.BackgroundColor = System.Drawing.Color.White;
            this.cmbGender.BorderColor = System.Drawing.Color.Silver;
            this.cmbGender.BorderRadius = 1;
            this.cmbGender.Color = System.Drawing.Color.Silver;
            this.cmbGender.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cmbGender.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbGender.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cmbGender.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cmbGender.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cmbGender.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbGender.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cmbGender.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cmbGender.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbGender.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbGender.FillDropDown = true;
            this.cmbGender.FillIndicator = false;
            this.cmbGender.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cmbGender.Font = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            this.cmbGender.ForeColor = System.Drawing.Color.Black;
            this.cmbGender.Icon = null;
            this.cmbGender.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbGender.IndicatorColor = System.Drawing.Color.DarkGray;
            this.cmbGender.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cmbGender.IndicatorThickness = 2;
            this.cmbGender.IsDropdownOpened = false;
            this.cmbGender.ItemBackColor = System.Drawing.Color.White;
            this.cmbGender.ItemBorderColor = System.Drawing.Color.White;
            this.cmbGender.ItemForeColor = System.Drawing.Color.Black;
            this.cmbGender.ItemHeight = 26;
            this.cmbGender.ItemHighLightColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.cmbGender.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cmbGender.Items.AddRange(new object[] {
            "ذكر",
            "أنثى"});
            this.cmbGender.ItemTopMargin = 3;
            bindingObject7.Data = "Gender";
            bindingObject7.Property = "Text";
            bindingObject7.TwoWay = true;
            this.bindingProvider.SetLink(this.cmbGender, bindingObject7);
            validationObject7.CustomErrorMessage = "";
            validationObject7.Optional = false;
            validationObject7.PropertyName = "Text";
            validationObject7.Regex = "(.|\\s)*\\S(.|\\s)*";
            validationObject7.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.cmbGender, validationObject7);
            themeOption7.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.cmbGender, themeOption7);
            this.cmbGender.Location = new System.Drawing.Point(33, 92);
            this.cmbGender.Name = "cmbGender";
            this.cmbGender.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.cmbGender.Size = new System.Drawing.Size(389, 32);
            this.cmbGender.TabIndex = 2;
            this.cmbGender.Text = null;
            this.cmbGender.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cmbGender.TextLeftMargin = 5;
            // 
            // lblDOB
            // 
            this.lblDOB.AutoSize = true;
            this.lblDOB.Font = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            bindingObject8.Data = "";
            bindingObject8.Property = "Text";
            bindingObject8.TwoWay = true;
            this.bindingProvider.SetLink(this.lblDOB, bindingObject8);
            themeOption8.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblDOB, themeOption8);
            validationObject8.CustomErrorMessage = "";
            validationObject8.Optional = false;
            validationObject8.PropertyName = "Text";
            validationObject8.Regex = null;
            validationObject8.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblDOB, validationObject8);
            this.lblDOB.Location = new System.Drawing.Point(463, 146);
            this.lblDOB.Name = "lblDOB";
            this.lblDOB.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblDOB.Size = new System.Drawing.Size(71, 22);
            this.lblDOB.TabIndex = 8;
            this.lblDOB.Text = "تاريخ الميلاد";
            // 
            // dtDOB
            // 
            this.dtDOB.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dtDOB.BackColor = System.Drawing.Color.White;
            this.dtDOB.BorderColor = System.Drawing.Color.Silver;
            this.dtDOB.BorderRadius = 1;
            this.dtDOB.CalendarMonthBackground = System.Drawing.Color.White;
            this.dtDOB.CalendarTitleBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.dtDOB.CalendarTitleForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.dtDOB.CalendarTrailingForeColor = System.Drawing.Color.Gray;
            this.dtDOB.Color = System.Drawing.Color.Silver;
            this.dtDOB.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtDOB.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtDOB.DisabledColor = System.Drawing.Color.Gray;
            this.dtDOB.DisplayWeekNumbers = false;
            this.dtDOB.DPHeight = 0;
            this.dtDOB.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtDOB.FillDatePicker = false;
            this.dtDOB.Font = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            this.dtDOB.ForeColor = System.Drawing.Color.Black;
            this.dtDOB.Icon = ((System.Drawing.Image)(resources.GetObject("dtDOB.Icon")));
            this.dtDOB.IconColor = System.Drawing.Color.Gray;
            this.dtDOB.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtDOB.LeftTextMargin = 5;
            bindingObject9.Data = "DOB";
            bindingObject9.Property = "Value";
            bindingObject9.TwoWay = true;
            this.bindingProvider.SetLink(this.dtDOB, bindingObject9);
            themeOption9.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.dtDOB, themeOption9);
            validationObject9.CustomErrorMessage = "";
            validationObject9.Optional = false;
            validationObject9.PropertyName = "Value";
            validationObject9.Regex = "";
            validationObject9.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.dtDOB, validationObject9);
            this.dtDOB.Location = new System.Drawing.Point(33, 146);
            this.dtDOB.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtDOB.Name = "dtDOB";
            this.dtDOB.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.dtDOB.Size = new System.Drawing.Size(389, 32);
            this.dtDOB.TabIndex = 3;
            this.dtDOB.Value = new System.DateTime(2023, 7, 25, 9, 25, 0, 0);
            // 
            // lblPhone
            // 
            this.lblPhone.AutoSize = true;
            this.lblPhone.Font = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            bindingObject10.Data = "";
            bindingObject10.Property = "Text";
            bindingObject10.TwoWay = true;
            this.bindingProvider.SetLink(this.lblPhone, bindingObject10);
            themeOption10.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblPhone, themeOption10);
            validationObject10.CustomErrorMessage = "";
            validationObject10.Optional = false;
            validationObject10.PropertyName = "Text";
            validationObject10.Regex = null;
            validationObject10.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblPhone, validationObject10);
            this.lblPhone.Location = new System.Drawing.Point(464, 200);
            this.lblPhone.Name = "lblPhone";
            this.lblPhone.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblPhone.Size = new System.Drawing.Size(70, 22);
            this.lblPhone.TabIndex = 15;
            this.lblPhone.Text = "رقم الهاتف";
            // 
            // txtPhone
            // 
            this.txtPhone.AcceptsReturn = false;
            this.txtPhone.AcceptsTab = false;
            this.txtPhone.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtPhone.AnimationSpeed = 200;
            this.txtPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPhone.AutoSizeHeight = true;
            this.txtPhone.BackColor = System.Drawing.Color.White;
            this.txtPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPhone.BackgroundImage")));
            this.txtPhone.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.txtPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.txtPhone.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPhone.BorderRadius = 1;
            this.txtPhone.BorderThickness = 1;
            this.txtPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.DefaultFont = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            this.txtPhone.DefaultText = "";
            this.txtPhone.FillColor = System.Drawing.Color.White;
            this.txtPhone.HideSelection = true;
            this.txtPhone.IconLeft = null;
            this.txtPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.IconPadding = 10;
            this.txtPhone.IconRight = null;
            this.txtPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.Lines = new string[0];
            bindingObject11.Data = "Phone";
            bindingObject11.Property = "Text";
            bindingObject11.TwoWay = true;
            this.bindingProvider.SetLink(this.txtPhone, bindingObject11);
            themeOption11.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.txtPhone, themeOption11);
            validationObject11.CustomErrorMessage = "";
            validationObject11.Optional = false;
            validationObject11.PropertyName = "Text";
            validationObject11.Regex = "^\\s*(?:\\+?(\\d{1,3}))?[-. (]*(\\d{3})[-. )]*(\\d{3})[-. ]*(\\d{4})(?: *x(\\d+))?\\s*$";
            validationObject11.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.txtPhone, validationObject11);
            this.txtPhone.Location = new System.Drawing.Point(33, 200);
            this.txtPhone.MaxLength = 32767;
            this.txtPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPhone.Modified = false;
            this.txtPhone.Multiline = false;
            this.txtPhone.Name = "txtPhone";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPhone.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnIdleState = stateProperties12;
            this.txtPhone.Padding = new System.Windows.Forms.Padding(3);
            this.txtPhone.PasswordChar = '\0';
            this.txtPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPhone.PlaceholderText = "";
            this.txtPhone.ReadOnly = false;
            this.txtPhone.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.txtPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPhone.SelectedText = "";
            this.txtPhone.SelectionLength = 0;
            this.txtPhone.SelectionStart = 0;
            this.txtPhone.ShortcutsEnabled = true;
            this.txtPhone.Size = new System.Drawing.Size(389, 45);
            this.txtPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPhone.TabIndex = 4;
            this.txtPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPhone.TextMarginBottom = 0;
            this.txtPhone.TextMarginLeft = 3;
            this.txtPhone.TextMarginTop = 1;
            this.txtPhone.TextPlaceholder = "";
            this.txtPhone.UseSystemPasswordChar = false;
            this.txtPhone.WordWrap = true;
            // 
            // lblEmail
            // 
            this.lblEmail.AutoSize = true;
            this.lblEmail.Font = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            bindingObject12.Data = "";
            bindingObject12.Property = "Text";
            bindingObject12.TwoWay = true;
            this.bindingProvider.SetLink(this.lblEmail, bindingObject12);
            themeOption12.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblEmail, themeOption12);
            validationObject12.CustomErrorMessage = "";
            validationObject12.Optional = false;
            validationObject12.PropertyName = "Text";
            validationObject12.Regex = null;
            validationObject12.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblEmail, validationObject12);
            this.lblEmail.Location = new System.Drawing.Point(439, 267);
            this.lblEmail.Name = "lblEmail";
            this.lblEmail.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblEmail.Size = new System.Drawing.Size(95, 22);
            this.lblEmail.TabIndex = 17;
            this.lblEmail.Text = "البريد الالكتروني";
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.AutoSizeHeight = true;
            this.txtEmail.BackColor = System.Drawing.Color.White;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmail.BorderRadius = 1;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            bindingObject13.Data = "Email";
            bindingObject13.Property = "Text";
            bindingObject13.TwoWay = true;
            this.bindingProvider.SetLink(this.txtEmail, bindingObject13);
            themeOption13.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.txtEmail, themeOption13);
            validationObject13.CustomErrorMessage = "";
            validationObject13.Optional = false;
            validationObject13.PropertyName = "Text";
            validationObject13.Regex = resources.GetString("validationObject13.Regex");
            validationObject13.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.txtEmail, validationObject13);
            this.txtEmail.Location = new System.Drawing.Point(33, 267);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties16;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(389, 45);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 5;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 3;
            this.txtEmail.TextMarginTop = 1;
            this.txtEmail.TextPlaceholder = "";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // lblDateJoined
            // 
            this.lblDateJoined.AutoSize = true;
            this.lblDateJoined.Font = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            bindingObject14.Data = "";
            bindingObject14.Property = "Text";
            bindingObject14.TwoWay = true;
            this.bindingProvider.SetLink(this.lblDateJoined, bindingObject14);
            themeOption14.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblDateJoined, themeOption14);
            validationObject14.CustomErrorMessage = "";
            validationObject14.Optional = false;
            validationObject14.PropertyName = "Text";
            validationObject14.Regex = null;
            validationObject14.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblDateJoined, validationObject14);
            this.lblDateJoined.Location = new System.Drawing.Point(459, 398);
            this.lblDateJoined.Name = "lblDateJoined";
            this.lblDateJoined.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblDateJoined.Size = new System.Drawing.Size(75, 22);
            this.lblDateJoined.TabIndex = 19;
            this.lblDateJoined.Text = "تاريخ الإضافة";
            // 
            // dtDateJoined
            // 
            this.dtDateJoined.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.dtDateJoined.BackColor = System.Drawing.Color.White;
            this.dtDateJoined.BorderColor = System.Drawing.Color.Silver;
            this.dtDateJoined.BorderRadius = 1;
            this.dtDateJoined.CalendarMonthBackground = System.Drawing.Color.White;
            this.dtDateJoined.CalendarTitleBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.dtDateJoined.CalendarTitleForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.dtDateJoined.CalendarTrailingForeColor = System.Drawing.Color.Gray;
            this.dtDateJoined.Color = System.Drawing.Color.Silver;
            this.dtDateJoined.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtDateJoined.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtDateJoined.DisabledColor = System.Drawing.Color.Gray;
            this.dtDateJoined.DisplayWeekNumbers = false;
            this.dtDateJoined.DPHeight = 0;
            this.dtDateJoined.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtDateJoined.FillDatePicker = false;
            this.dtDateJoined.Font = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            this.dtDateJoined.ForeColor = System.Drawing.Color.Black;
            this.dtDateJoined.Icon = ((System.Drawing.Image)(resources.GetObject("dtDateJoined.Icon")));
            this.dtDateJoined.IconColor = System.Drawing.Color.Gray;
            this.dtDateJoined.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtDateJoined.LeftTextMargin = 5;
            bindingObject15.Data = "DateJoined";
            bindingObject15.Property = "Value";
            bindingObject15.TwoWay = true;
            this.bindingProvider.SetLink(this.dtDateJoined, bindingObject15);
            themeOption15.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.dtDateJoined, themeOption15);
            validationObject15.CustomErrorMessage = "";
            validationObject15.Optional = false;
            validationObject15.PropertyName = "Value";
            validationObject15.Regex = "";
            validationObject15.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.dtDateJoined, validationObject15);
            this.dtDateJoined.Location = new System.Drawing.Point(34, 398);
            this.dtDateJoined.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtDateJoined.Name = "dtDateJoined";
            this.dtDateJoined.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.dtDateJoined.Size = new System.Drawing.Size(389, 32);
            this.dtDateJoined.TabIndex = 6;
            // 
            // lblNotes
            // 
            this.lblNotes.AutoSize = true;
            this.lblNotes.Font = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            bindingObject16.Data = "";
            bindingObject16.Property = "Text";
            bindingObject16.TwoWay = true;
            this.bindingProvider.SetLink(this.lblNotes, bindingObject16);
            themeOption16.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblNotes, themeOption16);
            validationObject16.CustomErrorMessage = "";
            validationObject16.Optional = false;
            validationObject16.PropertyName = "Text";
            validationObject16.Regex = null;
            validationObject16.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblNotes, validationObject16);
            this.lblNotes.Location = new System.Drawing.Point(471, 452);
            this.lblNotes.Name = "lblNotes";
            this.lblNotes.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.lblNotes.Size = new System.Drawing.Size(63, 22);
            this.lblNotes.TabIndex = 20;
            this.lblNotes.Text = "الملاحظات";
            // 
            // txtNotes
            // 
            this.txtNotes.AcceptsReturn = false;
            this.txtNotes.AcceptsTab = false;
            this.txtNotes.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtNotes.AnimationSpeed = 200;
            this.txtNotes.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNotes.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNotes.AutoSizeHeight = true;
            this.txtNotes.BackColor = System.Drawing.Color.White;
            this.txtNotes.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNotes.BackgroundImage")));
            this.txtNotes.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.txtNotes.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNotes.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.txtNotes.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNotes.BorderRadius = 1;
            this.txtNotes.BorderThickness = 1;
            this.txtNotes.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNotes.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNotes.DefaultFont = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            this.txtNotes.DefaultText = "";
            this.txtNotes.FillColor = System.Drawing.Color.White;
            this.txtNotes.HideSelection = true;
            this.txtNotes.IconLeft = null;
            this.txtNotes.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNotes.IconPadding = 10;
            this.txtNotes.IconRight = null;
            this.txtNotes.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNotes.Lines = new string[0];
            bindingObject17.Data = "Notes";
            bindingObject17.Property = "Text";
            bindingObject17.TwoWay = true;
            this.bindingProvider.SetLink(this.txtNotes, bindingObject17);
            themeOption17.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.txtNotes, themeOption17);
            validationObject17.CustomErrorMessage = "";
            validationObject17.Optional = true;
            validationObject17.PropertyName = "Text";
            validationObject17.Regex = "";
            validationObject17.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.txtNotes, validationObject17);
            this.txtNotes.Location = new System.Drawing.Point(33, 452);
            this.txtNotes.MaxLength = 32767;
            this.txtNotes.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNotes.Modified = false;
            this.txtNotes.Multiline = true;
            this.txtNotes.Name = "txtNotes";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNotes.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNotes.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNotes.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNotes.OnIdleState = stateProperties20;
            this.txtNotes.Padding = new System.Windows.Forms.Padding(3);
            this.txtNotes.PasswordChar = '\0';
            this.txtNotes.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNotes.PlaceholderText = "";
            this.txtNotes.ReadOnly = false;
            this.txtNotes.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.txtNotes.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNotes.SelectedText = "";
            this.txtNotes.SelectionLength = 0;
            this.txtNotes.SelectionStart = 0;
            this.txtNotes.ShortcutsEnabled = true;
            this.txtNotes.Size = new System.Drawing.Size(389, 128);
            this.txtNotes.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNotes.TabIndex = 7;
            this.txtNotes.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNotes.TextMarginBottom = 0;
            this.txtNotes.TextMarginLeft = 3;
            this.txtNotes.TextMarginTop = 1;
            this.txtNotes.TextPlaceholder = "";
            this.txtNotes.UseSystemPasswordChar = false;
            this.txtNotes.WordWrap = true;
            // 
            // lblBottom
            // 
            this.lblBottom.AutoSize = true;
            bindingObject18.Data = "";
            bindingObject18.Property = "Text";
            bindingObject18.TwoWay = true;
            this.bindingProvider.SetLink(this.lblBottom, bindingObject18);
            themeOption18.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.lblBottom, themeOption18);
            validationObject18.CustomErrorMessage = "";
            validationObject18.Optional = false;
            validationObject18.PropertyName = "Text";
            validationObject18.Regex = null;
            validationObject18.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.lblBottom, validationObject18);
            this.lblBottom.Location = new System.Drawing.Point(553, 839);
            this.lblBottom.Name = "lblBottom";
            this.lblBottom.Size = new System.Drawing.Size(0, 15);
            this.lblBottom.TabIndex = 23;
            // 
            // btnCancel
            // 
            this.btnCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCancel.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.btnCancel.FlatAppearance.BorderSize = 2;
            this.btnCancel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCancel.Font = new System.Drawing.Font("Droid Arabic Kufi", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            bindingObject19.Data = "";
            bindingObject19.Property = "Text";
            bindingObject19.TwoWay = true;
            this.bindingProvider.SetLink(this.btnCancel, bindingObject19);
            themeOption19.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.btnCancel, themeOption19);
            validationObject19.CustomErrorMessage = "";
            validationObject19.Optional = false;
            validationObject19.PropertyName = "Text";
            validationObject19.Regex = null;
            validationObject19.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.btnCancel, validationObject19);
            this.btnCancel.Location = new System.Drawing.Point(362, 749);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.btnCancel.Size = new System.Drawing.Size(80, 40);
            this.btnCancel.TabIndex = 13;
            this.btnCancel.Text = "إلغاء";
            this.btnCancel.UseVisualStyleBackColor = false;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnAdd
            // 
            this.btnAdd.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAdd.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.btnAdd.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.btnAdd.FlatAppearance.BorderSize = 2;
            this.btnAdd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAdd.Font = new System.Drawing.Font("Droid Arabic Kufi", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAdd.ForeColor = System.Drawing.Color.White;
            bindingObject20.Data = "";
            bindingObject20.Property = "Text";
            bindingObject20.TwoWay = true;
            this.bindingProvider.SetLink(this.btnAdd, bindingObject20);
            themeOption20.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.btnAdd, themeOption20);
            validationObject20.CustomErrorMessage = "";
            validationObject20.Optional = false;
            validationObject20.PropertyName = "Text";
            validationObject20.Regex = null;
            validationObject20.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.btnAdd, validationObject20);
            this.btnAdd.Location = new System.Drawing.Point(456, 749);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.btnAdd.Size = new System.Drawing.Size(80, 40);
            this.btnAdd.TabIndex = 12;
            this.btnAdd.Text = "حفظ";
            this.btnAdd.UseVisualStyleBackColor = false;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            // 
            // bunifuFormDock
            // 
            this.bunifuFormDock.AllowFormDragging = true;
            this.bunifuFormDock.AllowFormDropShadow = true;
            this.bunifuFormDock.AllowFormResizing = true;
            this.bunifuFormDock.AllowHidingBottomRegion = true;
            this.bunifuFormDock.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock.ContainerControl = this;
            this.bunifuFormDock.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock.DockingOptions.DockAll = true;
            this.bunifuFormDock.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock.DockingOptions.DockLeft = true;
            this.bunifuFormDock.DockingOptions.DockRight = true;
            this.bunifuFormDock.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock.DockingOptions.DockTopRight = true;
            this.bunifuFormDock.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock.ParentForm = this;
            this.bunifuFormDock.ShowCursorChanges = true;
            this.bunifuFormDock.ShowDockingIndicators = false;
            this.bunifuFormDock.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock.TitleBarOptions.BunifuFormDock = this.bunifuFormDock;
            this.bunifuFormDock.TitleBarOptions.DoubleClickToExpandWindow = false;
            this.bunifuFormDock.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            bindingObject2.Data = "";
            bindingObject2.Property = "Text";
            bindingObject2.TwoWay = true;
            this.bindingProvider.SetLink(this.label1, bindingObject2);
            themeOption2.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.label1, themeOption2);
            validationObject2.CustomErrorMessage = "";
            validationObject2.Optional = false;
            validationObject2.PropertyName = "Text";
            validationObject2.Regex = null;
            validationObject2.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.None;
            this.validationProvider.SetLink(this.label1, validationObject2);
            this.label1.Location = new System.Drawing.Point(480, 333);
            this.label1.Name = "label1";
            this.label1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.label1.Size = new System.Drawing.Size(54, 22);
            this.label1.TabIndex = 25;
            this.label1.Text = "التخصص";
            // 
            // bunifuTextBox1
            // 
            this.bunifuTextBox1.AcceptsReturn = false;
            this.bunifuTextBox1.AcceptsTab = false;
            this.bunifuTextBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuTextBox1.AnimationSpeed = 200;
            this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox1.AutoSizeHeight = true;
            this.bunifuTextBox1.BackColor = System.Drawing.Color.White;
            this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
            this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox1.BorderRadius = 1;
            this.bunifuTextBox1.BorderThickness = 1;
            this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Droid Arabic Kufi", 9F);
            this.bunifuTextBox1.DefaultText = "";
            this.bunifuTextBox1.FillColor = System.Drawing.Color.White;
            this.bunifuTextBox1.HideSelection = true;
            this.bunifuTextBox1.IconLeft = null;
            this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.IconPadding = 10;
            this.bunifuTextBox1.IconRight = null;
            this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.Lines = new string[0];
            bindingObject3.Data = "Specialization";
            bindingObject3.Property = "Text";
            bindingObject3.TwoWay = true;
            this.bindingProvider.SetLink(this.bunifuTextBox1, bindingObject3);
            themeOption3.Theme = Kimtoo.ThemeProvider.ThemeProvider.ThemeOption.theme_options.Default;
            this.themeProvider.SetLink(this.bunifuTextBox1, themeOption3);
            validationObject3.CustomErrorMessage = "";
            validationObject3.Optional = false;
            validationObject3.PropertyName = "Text";
            validationObject3.Regex = resources.GetString("validationObject3.Regex");
            validationObject3.ValidationType = Kimtoo.ValidationProvider.ValidationTypes.CustomRegex;
            this.validationProvider.SetLink(this.bunifuTextBox1, validationObject3);
            this.bunifuTextBox1.Location = new System.Drawing.Point(33, 333);
            this.bunifuTextBox1.MaxLength = 32767;
            this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox1.Modified = false;
            this.bunifuTextBox1.Multiline = false;
            this.bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox1.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(122)))), ((int)(((byte)(170)))), ((int)(((byte)(152)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnIdleState = stateProperties4;
            this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox1.PasswordChar = '\0';
            this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBox1.PlaceholderText = "";
            this.bunifuTextBox1.ReadOnly = false;
            this.bunifuTextBox1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox1.SelectedText = "";
            this.bunifuTextBox1.SelectionLength = 0;
            this.bunifuTextBox1.SelectionStart = 0;
            this.bunifuTextBox1.ShortcutsEnabled = true;
            this.bunifuTextBox1.Size = new System.Drawing.Size(389, 45);
            this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox1.TabIndex = 24;
            this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox1.TextMarginBottom = 0;
            this.bunifuTextBox1.TextMarginLeft = 3;
            this.bunifuTextBox1.TextMarginTop = 1;
            this.bunifuTextBox1.TextPlaceholder = "";
            this.bunifuTextBox1.UseSystemPasswordChar = false;
            this.bunifuTextBox1.WordWrap = true;
            // 
            // Frm_Doctor
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.WhiteSmoke;
            this.ClientSize = new System.Drawing.Size(599, 573);
            this.Controls.Add(this.pnlContent);
            this.Controls.Add(this.AppBar);
            this.DoubleBuffered = true;
            this.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.MaximizeBox = false;
            this.Name = "Frm_Doctor";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Frm_Doctor";
            this.Load += new System.EventHandler(this.Frm_Load);
            this.pnlContent.ResumeLayout(false);
            this.pnlContent.PerformLayout();
            this.ResumeLayout(false);

			}

        #region  Jenga Generated Code
        public void JengaInit(Color themeColor)
        {
            AppBar.BackColor = themeColor; 
            foreach (Control ctrl in pnlContent.Controls)
            {
                if (ctrl.GetType() == typeof(Bunifu.UI.WinForms.BunifuTextBox))
                {
                    var ctr = (Bunifu.UI.WinForms.BunifuTextBox)ctrl;
                    ctr.OnHoverState.BorderColor
                        = ctr.OnActiveState.BorderColor
                        = themeColor;

                }
                else if (ctrl.GetType() == typeof(Bunifu.UI.WinForms.BunifuDropdown))
                {
                    var ctr = (Bunifu.UI.WinForms.BunifuDropdown)ctrl;
                    ctr.ItemHighLightColor = themeColor;
                    ctr.ItemHighLightForeColor = Color.White;
                }
                else if (ctrl.GetType() == typeof(LinkLabel))
                {
                    var ctr = (LinkLabel)ctrl;
                    ctr.LinkColor
                        = ctr.VisitedLinkColor
                        = themeColor;
                }
                else if (ctrl.GetType() == typeof(Button))
                {
                    var ctr = (Button)ctrl;
                    ctr.FlatAppearance.BorderColor = themeColor;

                    if (ctr.Name == "btnAdd")
                        ctr.BackColor = themeColor;
                    else
                        ctr.ForeColor = themeColor;
                }
                else if (ctrl.GetType() == typeof(Bunifu.UI.WinForms.BunifuCheckBox))
                {
                    var ctr = (Bunifu.UI.WinForms.BunifuCheckBox)ctrl;
                    ctr.OnCheck.BorderColor = themeColor;
                    ctr.OnCheck.CheckBoxColor = themeColor;

                    ctr.OnUncheck.BorderColor = themeColor;
                    ctr.OnUncheck.CheckBoxColor = Color.WhiteSmoke;

                }

            }
        } 
        #endregion

			#endregion
			public Kimtoo.ValidationProvider.ValidationProvider validationProvider;
			public Kimtoo.BindingProvider.BindingProvider bindingProvider;
		    public Kimtoo.ThemeProvider.ThemeProvider themeProvider;
			public System.Windows.Forms.Button btnAdd;
			public System.Windows.Forms.Button btnCancel;
			public Bunifu.Utils.BunifuAppBar AppBar;
			public System.Windows.Forms.Panel pnlContent;
			public Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock;
			public Bunifu.UI.WinForms.BunifuSnackbar Alert;
		    public System.Windows.Forms.OpenFileDialog openFileDialog;
			public System.Windows.Forms.SaveFileDialog saveFileDialog;
public System.Windows.Forms.Label lblName;
public Bunifu.UI.WinForms.BunifuTextBox txtName;
public System.Windows.Forms.Label lblGender;
  public Bunifu.UI.WinForms.BunifuDropdown cmbGender;
public System.Windows.Forms.Label lblDOB;
public Bunifu.UI.WinForms.BunifuDatePicker dtDOB;
public System.Windows.Forms.Label lblPhone;
public Bunifu.UI.WinForms.BunifuTextBox txtPhone;
public System.Windows.Forms.Label lblEmail;
public Bunifu.UI.WinForms.BunifuTextBox txtEmail;
public System.Windows.Forms.Label lblDateJoined;
public Bunifu.UI.WinForms.BunifuDatePicker dtDateJoined;
public System.Windows.Forms.Label lblNotes;
public Bunifu.UI.WinForms.BunifuTextBox txtNotes;
public System.Windows.Forms.Label lblBottom;
        public Label label1;
        public Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        //declare
    }
			}