//Code Generated by Jenga.NET
			using System;
			using System.Collections.Generic;
			using System.ComponentModel;
			using System.Data;
			using System.Drawing;
			using System.Linq;
			using System.Text;
			using System.Threading.Tasks;
			using ServiceStack.OrmLite;
			using System.Windows.Forms; 
            using Newtonsoft.Json.Linq;
			using Jenga;
			//import;

			namespace PatientRecordManagement.Dialogs
			{

			public partial class Frm_Patient: Form
			{
			private PatientRecordManagement.Models.Patient _record;
			private PatientRecordManagement.Models.Patient _oldRecord;
            public Dictionary<string, object> FixedValues = new Dictionary<string, object>();

            public Func<PatientRecordManagement.Models.Patient, PatientRecordManagement.Models.Patient, bool> BeforeSave { get; set; } = null;
            public Action<PatientRecordManagement.Models.Patient> AfterSave { get; set; } = null;

			public Frm_Patient(Color themeColor,PatientRecordManagement.Models.Patient record = null, bool readOnly = false)
			{
			Cursor.Current = Cursors.WaitCursor;
			InitializeComponent();
			 //enable double buffer
            pnlContent.GetType()
               .GetProperty("DoubleBuffered", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic)
               .SetValue(pnlContent, true, null);
			 
			if(record==null)
			_record = new PatientRecordManagement.Models.Patient(); //create new recoded
			else
			_record = record; //assign existing record

			//bind data to dropdowns
			var db = Kt.Db;
		
                         
 
			//disable controls if read-only mode
			if (readOnly)
			{
			foreach (Control ctrl in pnlContent.Controls)
			{
			if (ctrl.GetType() != typeof(Label))
			ctrl.Enabled = false;
			btnCancel.Enabled = true;
			}
			}
             JengaInit(themeColor);
			Cursor.Current = Cursors.Default;
			}
			private void btnCancel_Click(object sender, EventArgs e)
			{
			this.Close();
			}
			private void btnAdd_Click(object sender, EventArgs e)
			{
		    try
            {
			
			//check validation
			if (validationProvider.Validate().Length > 0)
			{
			Alert.Show(this, "Vaidation Error", Bunifu.UI.WinForms.BunifuSnackbar.MessageTypes.Error);
			return;  //Return when validation fails
			}
			if (BeforeSave != null)
                 if (!BeforeSave.Invoke(_oldRecord, _record))
                        return;
			Kt.Db.Save(_record) ; //save changes to database
			 if (AfterSave != null)
                    AfterSave.Invoke(_record);
			Alert.Show(this, "Successfull", Bunifu.UI.WinForms.BunifuSnackbar.MessageTypes.Success);
			 }
            catch (Exception err)
            {
                Alert.Show(this, err.Message, Bunifu.UI.WinForms.BunifuSnackbar.MessageTypes.Error);
            }
			}
			  private void Frm_Load(object sender, EventArgs e) 
			  {
				    //check fixed Values
					if (this.FixedValues.Count() > 0)
					{
						//disable mentioned controls
						foreach (Control ctrl in pnlContent.Controls)
							   if (bindingProvider.GetLink(ctrl) != null && FixedValues.ContainsKey(bindingProvider.GetLink(ctrl).Data))
								ctrl.Enabled = false;

						//merge the pased values
						var tmp = JObject.FromObject(_record);
						foreach (var prop in this.FixedValues)
							tmp[prop.Key] = JToken.Parse(prop.Value.ToString());

						_record = tmp.ToObject<PatientRecordManagement.Models.Patient>();
					}

            //bind record to controls
            bindingProvider.Bind(_record);
				  /**load**/
			  }

        private void lblName_Click(object sender, EventArgs e)
        {

        }

        private void txtEmail_TextChanged(object sender, EventArgs e)
        {

        }

        private void lblGender_Click(object sender, EventArgs e)
        {

        }

        private void cmbGender_SelectedIndexChanged(object sender, EventArgs e)
        {

        }

        private void txtPolicyNo_TextChanged(object sender, EventArgs e)
        {

        }

        private void lblEmail_Click(object sender, EventArgs e)
        {

        }

        private void lblPhone_Click(object sender, EventArgs e)
        {

        }

        private void txtPhone_TextChanged(object sender, EventArgs e)
        {

        }

        private void txtLName_TextChanged(object sender, EventArgs e)
        {

        }

        private void bunifuTextBox6_TextChanged(object sender, EventArgs e)
        {

        }

        private void bunifuTextBox8_TextChanged(object sender, EventArgs e)
        {

        }

        private void bunifuTextBox9_TextChanged(object sender, EventArgs e)
        {

        }

        private void pnlContent_Paint(object sender, PaintEventArgs e)
        {

        }

        private void txtName_TextChanged(object sender, EventArgs e)
        {

        }

        private void AppBar_IconClick(object sender, EventArgs e)
        {

        }

        private void label9_Click(object sender, EventArgs e)
        {

        }

        private void label10_Click(object sender, EventArgs e)
        {

        }

        private void label8_Click(object sender, EventArgs e)
        {

        }

        private void label4_Click(object sender, EventArgs e)
        {

        }

        private void label6_Click(object sender, EventArgs e)
        {

        }

        private void label7_Click(object sender, EventArgs e)
        {

        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void lblDOB_Click(object sender, EventArgs e)
        {

        }

        private void label2_Click(object sender, EventArgs e)
        {

        }

        private void label3_Click(object sender, EventArgs e)
        {

        }
    }
			}